@LearningAPI_HostAddress = https://localhost:7004
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZ2l2ZW5fbmFtZSI6IlN0aWxsIiwiZmFtaWx5X25hbWUiOiJXYXRlciIsImVtYWlsIjoidGVzdEBueXAuZWR1LnNnIiwiUG9zdGFsQ29kZSI6IjExMTExMSIsInJvbGUiOiJVc2VyIiwibmJmIjoxNzM4NjU1ODkxLCJleHAiOjE3NDEyNDc4OTEsImlhdCI6MTczODY1NTg5MX0.RWSfty_eBrn7ofSi0Y3CtcIRsbn9Tv_Z8JvKSGgF_jU
// user

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
  "FirstName": "Still",
  "LastName": "Water",
  "Email": "test@nyp.edu.sg",
  "Password": "password@123",
  "PostalCode": "111111"
}
### register

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
 "email": "test@nyp.edu.sg",
 "password": "password@123"
}
### login

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}

### auth


@userid=4
GET {{LearningAPI_HostAddress}}/user/{{userid}}

### get single user

GET {{LearningAPI_HostAddress}}/user/all

### get all user

PUT {{LearningAPI_HostAddress}}/user/{{userid}}
Content-Type: application/json

{
  "FirstName": "Leroy",
  "LastName": "Jenkins",
  "Email": "test@nyp.edu.sg",
  "PostalCode": "111111"
}

### update single user

PUT {{LearningAPI_HostAddress}}/user/activate/{{userid}}

### activate user

PUT {{LearningAPI_HostAddress}}/user/deactivate/{{userid}}

### deactivate user





@admintoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5iZiI6MTczNjg2NDc0NCwiZXhwIjoxNzM5NDU2NzQ0LCJpYXQiOjE3MzY4NjQ3NDR9.IlLF203zFWf0UQ359nYArz4Pp1IVxggH52Kr_xrJTbE

// admin
POST {{LearningAPI_HostAddress}}/admin/register
Content-Type: application/json

{
  "Email": "admin@example.com",
  "Password": "password@123"
}

### register


POST {{LearningAPI_HostAddress}}/admin/login
Content-Type: application/json

{
  "Email": "admin@example.com",
  "Password": "password@123"
}

### login


GET {{LearningAPI_HostAddress}}/admin/all

### get all admin

@adminid=1

GET {{LearningAPI_HostAddress}}/admin/{{adminid}}

### get 1 admin

PUT {{LearningAPI_HostAddress}}/admin/{{adminid}}
Content-Type: application/json

{
  "Email": "greenthread@example.com",
  "Password": "password@123"
}

### update

GET {{LearningAPI_HostAddress}}/admin/auth
Authorization: Bearer {{admintoken}}


###

PUT {{LearningAPI_HostAddress}}/admin/activate/{{adminid}}

### activate admin

PUT {{LearningAPI_HostAddress}}/admin/deactivate/{{adminid}}

### deactivate admin



POST {{LearningAPI_HostAddress}}/api/product
Content-Type: application/json
{
  "productName": "Men's T-Shirt",
  "productDescription": "High-quality cotton t-shirt.",
  "price": 29.99,
  "stock": 100,
  "size": "S",   
  "discountPercentage": 10,
  "status": "Active",
  "productCategoryID": 1
}







###

POST {{LearningAPI_HostAddress}}/api/productcategory
Content-Type: application/json

{
  
  "productCategoryName": "Clothing"
}
###


POST {{LearningAPI_HostAddress}}/api/shoppingcart
Content-Type: application/json

{
  "userID": 1,
  "productID": 2,
  "quantity": 2
}

###
POST {{LearningAPI_HostAddress}}/api/shoppingcart/1
Content-Type: application/json

{
  "quantity": 10
}

###

POST {{LearningAPI_HostAddress}}/api/payment
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "userID": 1,
  "shoppingCartID": 1,
  "address": "123 Green Street, New York",
  "phoneNumber": "1234567890",
  "paymentMethod": "Credit Card",
  "amountPaid": 59.99
}


###



POST {{LearningAPI_HostAddress}}/api/order
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "userID": 1,
  "paymentID": 1,
  "grandTotal": 119.96
}


###
