@LearningAPI_HostAddress = https://localhost:7004
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZ2l2ZW5fbmFtZSI6IlN0aWxsIiwiZmFtaWx5X25hbWUiOiJXYXRlciIsImVtYWlsIjoidGVzdEBueXAuZWR1LnNnIiwiUG9zdGFsQ29kZSI6IjExMTExMSIsInJvbGUiOiJVc2VyIiwibmJmIjoxNzM4NjgzNDIxLCJleHAiOjE3NDEyNzU0MjEsImlhdCI6MTczODY4MzQyMX0.OB-Ue-0NStyFkGMHlS778N-5S6GXSTCrkjkiY5FMiJc
// user

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
  "FirstName": "Still",
  "LastName": "Water",
  "Email": "test@nyp.edu.sg",
  "Password": "password@123",
  "PostalCode": "111111"
}
### register

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
 "email": "test@nyp.edu.sg",
 "password": "password@123"
}
### login

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}

### auth


@userid=4
GET {{LearningAPI_HostAddress}}/user/{{userid}}

### get single user

GET {{LearningAPI_HostAddress}}/user/all

### get all user

PUT {{LearningAPI_HostAddress}}/user/{{userid}}
Content-Type: application/json

{
  "FirstName": "Leroy",
  "LastName": "Jenkins",
  "Email": "test@nyp.edu.sg",
  "PostalCode": "111111"
}

### update single user

PUT {{LearningAPI_HostAddress}}/user/activate/{{userid}}

### activate user

PUT {{LearningAPI_HostAddress}}/user/deactivate/{{userid}}

### deactivate user





@admintoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5iZiI6MTczNjg2NDc0NCwiZXhwIjoxNzM5NDU2NzQ0LCJpYXQiOjE3MzY4NjQ3NDR9.IlLF203zFWf0UQ359nYArz4Pp1IVxggH52Kr_xrJTbE

// admin
POST {{LearningAPI_HostAddress}}/admin/register
Content-Type: application/json

{
  "Email": "admin@example.com",
  "Password": "password@123"
}

### register


POST {{LearningAPI_HostAddress}}/admin/login
Content-Type: application/json

{
  "Email": "admin@example.com",
  "Password": "password@123"
}

### login


GET {{LearningAPI_HostAddress}}/admin/all

### get all admin

@adminid=1

GET {{LearningAPI_HostAddress}}/admin/{{adminid}}

### get 1 admin

PUT {{LearningAPI_HostAddress}}/admin/{{adminid}}
Content-Type: application/json

{
  "Email": "greenthread@example.com",
  "Password": "password@123"
}

### update

GET {{LearningAPI_HostAddress}}/admin/auth
Authorization: Bearer {{admintoken}}


###

PUT {{LearningAPI_HostAddress}}/admin/activate/{{adminid}}

### activate admin

PUT {{LearningAPI_HostAddress}}/admin/deactivate/{{adminid}}

### deactivate admin


POST {{LearningAPI_HostAddress}}/api/product
Content-Type: application/json

{
  "productName": "Men's T-Shirt",
  "productDescription": "High-quality cotton t-shirt.",
  "price": 29.99,
  "stock": 100,
  "size": "S",
  "discountPercentage": 10,
  "status": "Active",
  "category": "Shirt"
}


###

GET {{LearningAPI_HostAddress}}/api/product
Content-Type: application/json


###



POST {{LearningAPI_HostAddress}}/api/shoppingcart
Content-Type: application/json

{
  "userID": 5,
  "productID": 2,
  "quantity": 20
}

###

GET {{LearningAPI_HostAddress}}/api/shoppingcart/
Content-Type: application/json


###
PUT {{LearningAPI_HostAddress}}/api/shoppingcart/1
Content-Type: application/json

{
  "quantity": 10
}

###

POST {{LearningAPI_HostAddress}}/api/payment
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "userID": 5,
  "shoppingCartID": 27,
  "address": "123 Green Street, New York",
  "phoneNumber": "1234567890",
  "paymentMethod": "Credit Card",
  "amountPaid": 59.99
}


###
GET {{LearningAPI_HostAddress}}/api/payment
Content-Type: application/json
Authorization: Bearer {{token}}

###



POST {{LearningAPI_HostAddress}}/api/order
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "userID": 5,
  "paymentID": 27,
  "grandTotal": 30.00
}

###



GET {{LearningAPI_HostAddress}}/api/order
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{LearningAPI_HostAddress}}/api/delivery
Content-Type: application/json

{
  "orderID": 1,
  "address": "123 Green Street, New York, NY 10001",
  "deliveryStatus": "Pending"
}

###

POST {{LearningAPI_HostAddress}}/api/refund
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "orderID": 1,
  "refundAmount": 50.00
}


###

GET {{LearningAPI_HostAddress}}/api/refund

###

POST {{LearningAPI_HostAddress}}/api/customerservice
Content-Type: application/json

{
  "comment": "I received a defective item and need a replacement.",
  "status": "Pending",
  "needReply": true,
  "adminNote": "",
  "userID": 1
}


###

GET {{LearningAPI_HostAddress}}/api/customerservice

###
